api:
  restart: always
  build: ./api
  expose:
    - "8000"
  volumes:
    - /usr/src/apps

docs:
  image: busybox
  volumes:
    - ./docs/build:/var/www/html/docs

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes_from:
    - api
    - docs
  links:
    - api:api
